version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 2

phases:
  install:
    commands:
      - echo 'Installing Python dependencies'
      - sudo yum install -y python3 python3-pip 
      - python3 -m ensurepip --upgrade 
      - python3 -m pip install django
  pre_build:
    commands:
      - echo 'Prebuild'
  build:
    commands:
      - echo 'Running Django Tests'
      - codebuild-tests-run --test-command 'python manage.py test calculator' --files-search "codebuild-glob-search '**/tests/*test_*.py'" --sharding-strategy 'equal-distribution'
  post_build:
    commands:
      - echo "Would deploy here"
